name: release

on: push
permissions:
  contents: write

jobs:
  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
    - name: Prepare release notes
      run: uv tool run git-changelog --release-notes > release-notes.md
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:

   pypi-publish:
    name: Upload release to PyPI
    needs:
      - release
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: pypi
      url: https://pypi.org/p/nomad-tools
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install build python package
        run: pip install --upgrade build
      - name: build the package
        run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1       body_path: release-notes.md
